name: Run bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-container:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install jq
      run: sudo apt update && sudo apt install jq

    - name: Download timestamp from the last successful run
      run: |
        RUN_ID=$(curl --silent --show-error \
          --header "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          --url "https://api.github.com/repos/${{ github.repository }}/actions/workflows/bot.yaml/runs" \
          | jq '[.workflow_runs[] | select(.conclusion == "success")][0].id')
        
        if [ "$RUN_ID" != "null" ]; then
          echo "Downloading artifact from run ID $RUN_ID"
          curl --silent --show-error \
            --header "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            --location \
            --url "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/artifacts" \
            | jq -r '.artifacts[] | select(.name == "timestamp") | .archive_download_url' \
            | xargs curl --silent --show-error \
              --header "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
              --location \
              --output timestamp.zip
          unzip -o timestamp.zip
        else
          echo "No successful runs found."
        fi

    - name: Run Docker container
      run: |
        touch timestamp && cat timestamp
        docker run --env BLUE_LOGIN=${{ secrets.BLUE_LOGIN }} --env BLUE_PASSWORD=${{ secrets.BLUE_PASSWORD }} -v $(pwd)/timestamp:/timestamp calibro/resetera-nt-atproto:latest
        
    - name: Upload timestamp
      uses: actions/upload-artifact@v2
      with:
        name: timestamp
        path: timestamp
